export const DEFAULT_TIMELINE = [
  {
    id: "2002-sandur-council",
    file: "/images/work/oath.jpg",
    name: "Sandur Town Municipal Council",
    type: "Political Journey",
    year: "2002",
    text: "Elected for the first time as a Member of the Sandur Town Municipal Council in Ballari district, marking the beginning of his public and political journey.",
    textKn: "ಬಳ್ಳಾರಿ ಜಿಲ್ಲೆಯ ಸಂಡೂರು ಪಟ್ಟಣ ಪುರಸಭೆಯ ಸದಸ್ಯರಾಗಿ ಮೊದಲ ಬಾರಿಗೆ ಆಯ್ಕೆಯಾಗಿ ಸಾರ್ವಜನಿಕ ಮತ್ತು ರಾಜಕೀಯ ಪ್ರಯಾಣವನ್ನು ಆರಂಭಿಸಿದರು.",
    titleKn: "ಸಂಡೂರು ಪಟ್ಟಣ ಪುರಸಭೆ",
  },
  {
    id: "2004-mla-sandur",
    file: "/images/portraits/hero.jpg",
    name: "First term as MLA, Sandur",
    type: "Legislative Mandate",
    year: "2004",
    text: "Contested the Karnataka Legislative Assembly election from the Sandur Constituency on a Janata Dal (Secular) ticket and secured a remarkable mandate, entering the Karnataka Legislative Assembly for the first time.",
    textKn: "ಜನತಾ ದಳ (ಜಾತ್ಯಾತೀತ) ಟಿಕೆಟ್‌ನಲ್ಲಿ ಸಂಡೂರು ಕ್ಷೇತ್ರದಿಂದ ಕರ್ನಾಟಕ ವಿಧಾನಸಭಾ ಚುನಾವಣೆಗೆ ಸ್ಪರ್ಧಿಸಿ ಗಮನಾರ್ಹ ಜನಾದೇಶ ಪಡೆದು ಮೊದಲ ಬಾರಿಗೆ ವಿಧಾನಸಭೆಗೆ ಪ್ರವೇಶಿಸಿದರು.",
    titleKn: "ಮೊದಲ ಅವಧಿ ಶಾಸಕರು, ಸಂಡೂರು",
  },
  {
    id: "2007-joined-inc",
    file: "/images/portraits/namaste.jpg",
    name: "Joined Indian National Congress",
    type: "Party Leadership",
    year: "2007",
    text: "Joined the Indian National Congress under the guidance and leadership of Shri Siddaramaiah amidst the changing political landscape of the state.",
    textKn: "ರಾಜ್ಯದ ಬದಲಾಗುತ್ತಿದ್ದ ರಾಜಕೀಯ ಪರಿಸರದಲ್ಲಿ ಶ್ರೀ ಸಿದ್ದರಾಮಯ್ಯ ಅವರ ಮಾರ್ಗದರ್ಶನ ಮತ್ತು ನಾಯಕತ್ವದಲ್ಲಿ ಭಾರತೀಯ ರಾಷ್ಟ್ರೀಯ ಕಾಂಗ್ರೆಸ್ ಸೇರಿದರು.",
    titleKn: "ಭಾರತೀಯ ರಾಷ್ಟ್ರೀಯ ಕಾಂಗ್ರೆಸ್ ಸೇರ್ಪಡೆ",
  },
  {
    id: "2008-mla-kalaghatagi",
    file: "/images/portraits/about.jpg",
    name: "Second term, Kalaghatagi",
    type: "Re-election Mandate",
    year: "2008",
    text: "Following the constituency delimitation process, Sandur was reserved as a Scheduled Tribe constituency. He contested from the Kalaghatagi Assembly Constituency in Dharwad district and registered a resounding victory.",
    textKn: "ಕ್ಷೇತ್ರ ಪುನರ್‌ವಿಂಗಡಣೆಯ ನಂತರ ಸಂಡೂರು ಪರಿಶಿಷ್ಟ ಪಂಗಡಕ್ಕೆ ಮೀಸಲಾಯಿತು. ಧಾರವಾಡ ಜಿಲ್ಲೆಯ ಕಲಘಟಗಿ ವಿಧಾನಸಭಾ ಕ್ಷೇತ್ರದಿಂದ ಸ್ಪರ್ಧಿಸಿ ಅಭೂತಪೂರ್ವ ಗೆಲುವು ಸಾಧಿಸಿ ಎರಡನೇ ಅವಧಿಗೆ ಶಾಸಕರಾದರು.",
    titleKn: "ಎರಡನೇ ಅವಧಿ, ಕಲಘಟಗಿ",
  },
  {
    id: "2010-kpcc-gen-sec",
    file: "/images/work/students.jpg",
    name: "KPCC General Secretary",
    type: "State Leadership",
    year: "2010",
    text: "Appointed as General Secretary of the Karnataka Pradesh Congress Committee, where he played a significant role in strengthening and expanding the party organisation across the state.",
    textKn: "ಕರ್ನಾಟಕ ಪ್ರದೇಶ ಕಾಂಗ್ರೆಸ್ ಸಮಿತಿಯ ಸಾಮಾನ್ಯ ಕಾರ್ಯದರ್ಶಿಯಾಗಿ ನೇಮಕಗೊಂಡು ರಾಜ್ಯಾದ್ಯಂತ ಪಕ್ಷ ಸಂಘಟನೆಯನ್ನು ಬಲಪಡಿಸುವಲ್ಲಿ ಮಹತ್ವದ ಪಾತ್ರ ವಹಿಸಿದರು.",
    titleKn: "ಕೆಪಿಸಿಸಿ ಸಾಮಾನ್ಯ ಕಾರ್ಯದರ್ಶಿ",
  },
  {
    id: "2010-ballari-padayatra",
    file: "/images/work/children.jpg",
    name: "Ballari Padayatra",
    type: "Historic Movement",
    year: "2010",
    text: "Participated in the historic Ballari Padayatra, a landmark movement in Karnataka’s political history.",
    textKn: "ಕರ್ನಾಟಕದ ರಾಜಕೀಯ ಇತಿಹಾಸದಲ್ಲಿ ಮೈಲಿಗಲ್ಲಾದ ಐತಿಹಾಸಿಕ ಬಳ್ಳಾರಿ ಪಾದಯಾತ್ರೆಯಲ್ಲಿ ಭಾಗವಹಿಸಿದರು.",
    titleKn: "ಬಳ್ಳಾರಿ ಪಾದಯಾತ್ರೆ",
  },
  {
    id: "2011-kpcc-raichur",
    file: "/images/work/gig-meet.jpg",
    name: "KPCC in-charge, Raichur",
    type: "District Outreach",
    year: "2011",
    text: "Appointed by the KPCC as the party’s in-charge for Raichur district, further contributing to organisational development and grassroots outreach.",
    textKn: "ಕೆಪಿಸಿಸಿಯಿಂದ ರಾಯಚೂರು ಜಿಲ್ಲೆಯ ಪಕ್ಷ ಉಸ್ತುವಾರಿಯಾಗಿ ನೇಮಕಗೊಂಡು ಸಂಘಟನಾ ಅಭಿವೃದ್ಧಿ ಮತ್ತು ತಳಮಟ್ಟದ ಸಂಪರ್ಕಕ್ಕೆ ಕೊಡುಗೆ ನೀಡಿದರು.",
    titleKn: "ಕೆಪಿಸಿಸಿ ಉಸ್ತುವಾರಿ, ರಾಯಚೂರು",
  },
  {
    id: "2013-third-term",
    file: "/images/work/health-launch.jpg",
    name: "Third term, Landslide mandate",
    type: "Massive Victory",
    year: "2013",
    text: "Achieved a landslide victory from the Kalaghatagi Assembly Constituency with a margin of over 45,600 votes, earning a third consecutive term in the Assembly.",
    textKn: "ಕಲಘಟಗಿ ವಿಧಾನಸಭಾ ಕ್ಷೇತ್ರದಿಂದ 45,600ಕ್ಕೂ ಹೆಚ್ಚು ಮತಗಳ ಅಂತರದಲ್ಲಿ ಭಾರಿ ಗೆಲುವು ಸಾಧಿಸಿ ಸತತ ಮೂರನೇ ಅವಧಿಗೆ ಕರ್ನಾಟಕ ವಿಧಾನಸಭೆಗೆ ಆಯ್ಕೆಯಾದರು.",
    titleKn: "ಮೂರನೇ ಅವಧಿ, ಭಾರಿ ಜನಾದೇಶ",
  },
  {
    id: "2013-info-minister",
    file: "/images/work/oath.jpg",
    name: "Minister for Information & Infra",
    type: "Cabinet Minister",
    year: "2013",
    text: "Sworn in as Minister for Information and Public Relations and Infrastructure Development in the cabinet led by Chief Minister Shri Siddaramaiah.",
    textKn: "ಮುಖ್ಯಮಂತ್ರಿ ಶ್ರೀ ಸಿದ್ದರಾಮಯ್ಯ ನೇತೃತ್ವದ ಸಂಪುಟದಲ್ಲಿ ಮಾಹಿತಿ ಮತ್ತು ಸಾರ್ವಜನಿಕ ಸಂಪರ್ಕ ಹಾಗೂ ಮೂಲಸೌಕರ್ಯ ಅಭಿವೃದ್ಧಿ ಸಚಿವರಾಗಿ ಪ್ರಮಾಣವಚನ ಸ್ವೀಕರಿಸಿದರು.",
    titleKn: "ಮಾಹಿತಿ, ಸಾರ್ವಜನಿಕ ಸಂಪರ್ಕ ಮತ್ತು ಮೂಲಸೌಕರ್ಯ ಅಭಿವೃದ್ಧಿ ಸಚಿವರು",
  },
  {
    id: "2013-uttarakhand-rescue",
    file: "/images/rescue/pahalgam.jpg",
    name: "Uttarakhand Rescue Operation",
    type: "Humanitarian Rescue",
    year: "2013",
    text: "During the devastating Uttarakhand floods, he was entrusted with the responsibility of rescuing stranded Kannadigas. Through his dedicated efforts, all affected citizens were safely brought back to Karnataka.",
    textKn: "ಉತ್ತರಾಖಂಡದ ವಿನಾಶಕಾರಿ ಪ್ರವಾಹದಲ್ಲಿ ಸಿಲುಕಿದ್ದ ಕನ್ನಡಿಗರನ್ನು ರಕ್ಷಿಸುವ ಹೊಣೆ ವಹಿಸಲಾಯಿತು. ಸಮರ್ಪಿತ ಪ್ರಯತ್ನದಿಂದ ಎಲ್ಲಾ ಪೀಡಿತರನ್ನು ಸುರಕ್ಷಿತವಾಗಿ ಕರ್ನಾಟಕಕ್ಕೆ ಕರೆತಂದು ಮೆಚ್ಚುಗೆ ಪಡೆದರು.",
    titleKn: "ಉತ್ತರಾಖಂಡ ರಕ್ಷಣಾ ಕಾರ್ಯ",
  },
  {
    id: "2016-labour-minister",
    file: "/images/work/gig-meet.jpg",
    name: "Minister for Labour & Skill",
    type: "Cabinet Reform",
    year: "2016",
    text: "Assumed office as Minister for Labour and Skill Development, ushering in a series of transformative reforms and welfare initiatives for workers and youth across Karnataka.",
    textKn: "ಕಾರ್ಮಿಕ ಮತ್ತು ಕೌಶಲ್ಯ ಅಭಿವೃದ್ಧಿ ಸಚಿವರಾಗಿ ಅಧಿಕಾರ ವಹಿಸಿ, ಕರ್ನಾಟಕದಾದ್ಯಂತ ಕಾರ್ಮಿಕರು ಮತ್ತು ಯುವಜನರಿಗೆ ಪರಿವರ್ತನಕಾರಿ ಸುಧಾರಣೆಗಳು ಮತ್ತು ಕಲ್ಯಾಣ ಉಪಕ್ರಮಗಳನ್ನು ತಂದರು.",
    titleKn: "ಕಾರ್ಮಿಕ ಮತ್ತು ಕೌಶಲ್ಯ ಅಭಿವೃದ್ಧಿ ಸಚಿವರು",
  },
  {
    id: "2022-bharat-jodo",
    file: "/images/portraits/hero.jpg",
    name: "Bharat Jodo Yatra & KPCC VP",
    type: "National Movement",
    year: "2022",
    text: "Actively participated in the historic Bharat Jodo Yatra alongside Shri Rahul Gandhi and appointed Vice President of the Karnataka Pradesh Congress Committee.",
    textKn: "ಐತಿಹಾಸಿಕ ಭಾರತ ಜೋಡೋ ಯಾತ್ರೆಯಲ್ಲಿ ಶ್ರೀ ರಾಹುಲ್ ಗಾಂಧಿ ಅವರೊಂದಿಗೆ ನಡೆದು ಕೆಪಿಸಿಸಿ ಉಪಾಧ್ಯಕ್ಷರಾಗಿ ಸೇವೆ ಸಲ್ಲಿಸಿದರು.",
    titleKn: "ಭಾರತ ಜೋಡೋ ಯಾತ್ರೆ & ಕೆಪಿಸಿಸಿ ಉಪಾಧ್ಯಕ್ಷರು",
  },
  {
    id: "2023-fourth-term",
    file: "/images/portraits/namaste.jpg",
    name: "Fourth term as MLA",
    type: "People's Mandate",
    year: "2023",
    text: "Re-elected from the Kalaghatagi Assembly Constituency, securing his fourth term as a Member of the Karnataka Legislative Assembly.",
    textKn: "ಕಲಘಟಗಿ ವಿಧಾನಸಭಾ ಕ್ಷೇತ್ರದಿಂದ ಮರು ಆಯ್ಕೆಯಾಗಿ ಕರ್ನಾಟಕ ವಿಧಾನಸಭೆಯಲ್ಲಿ ನಾಲ್ಕನೇ ಅವಧಿಗೆ ಶಾಸಕರಾದರು.",
    titleKn: "ನಾಲ್ಕನೇ ಅವಧಿ ಶಾಸಕರು",
  },
  {
    id: "2023-labour-minister-current",
    file: "/images/work/oath.jpg",
    name: "Minister for Labour",
    type: "Cabinet Portfolio",
    year: "2023",
    text: "Inducted into the Government of Karnataka as Minister for Labour.",
    textKn: "ಕರ್ನಾಟಕ ಸರ್ಕಾರಕ್ಕೆ ಕಾರ್ಮικ ಸಚಿವರಾಗಿ ಸೇರ್ಪಡೆಯಾದರು.",
    titleKn: "ಕಾರ್ಮಿಕ ಸಚಿವರು",
  },
  {
    id: "2023-dharwad-incharge",
    file: "/images/portraits/about.jpg",
    name: "District In-charge Minister, Dharwad",
    type: "District Leadership",
    year: "2023",
    text: "Appointed as the District In-charge Minister for Dharwad, taking on the responsibility of overseeing developmental initiatives across the district.",
    textKn: "ಧಾರವಾಡ ಜಿಲ್ಲಾ ಉಸ್ತುವಾರಿ ಸಚಿವರಾಗಿ ನೇಮಕಗೊಂಡು ಜಿಲ್ಲೆಯಾದ್ಯಂತ ಅಭಿವೃದ್ಧಿ ಉಪಕ್ರಮಗಳ ಮೇಲ್ವಿಚಾರಣೆ ಹೊಣೆ ವಹಿಸಿದರು.",
    titleKn: "ಜಿಲ್ಲಾ ಉಸ್ತುವಾರಿ ಸಚಿವರು, ಧಾರವಾಡ",
  }
];

export const PROJECTS = DEFAULT_TIMELINE;
export const IMAGE_FILES = PROJECTS.map((p) => p.file);
